package orchestrator

import (
	"errors"
	"testing"
)

func TestValidateApprovalChoiceHonorsRevisionBoundary(t *testing.T) {
	t.Parallel()
	if err := validateApprovalChoice("Approve", 0); err != nil {
		t.Fatalf("Approve error = %v, want nil", err)
	}
	if err := validateApprovalChoice("Accept as-is", 2); !errors.Is(err, ErrInvalidDecision) {
		t.Fatalf("Accept as-is below revision boundary error = %v, want ErrInvalidDecision", err)
	}
	if err := validateApprovalChoice("Accept as-is", 3); err != nil {
		t.Fatalf("Accept as-is at revision boundary error = %v, want nil", err)
	}
}

func TestDecisionValidationRejectsSelfAttributionAndMasksExamples(t *testing.T) {
	t.Parallel()

	approvalVectors := []struct {
		name string
		text string
		want bool
	}{
		{name: "generated by assistant", text: "This approval was generated by the assistant.", want: true},
		{name: "assistant initiated", text: "assistant-initiated approval", want: true},
		{name: "conductor selected", text: "The conductor selected this choice.", want: true},
		{name: "conductor default", text: "A. conductor default", want: true},
		{name: "quoted example", text: `The prompt says "assistant-generated approval".`, want: false},
		{name: "inline code example", text: "Use `assistant-initiated approval` as an example.", want: false},
		{name: "block quote example", text: "> assistant-generated approval\n\nHuman context follows.", want: false},
		{name: "unknown wording", text: "The review recommendation is conservative.", want: false},
	}
	for _, vector := range approvalVectors {
		vector := vector
		t.Run(vector.name, func(t *testing.T) {
			t.Parallel()
			got := selfAttributedDecisionMarker(vector.text, decisionKindApproval) != nil
			if got != vector.want {
				t.Fatalf("selfAttributedDecisionMarker(%q) = %v, want %v", vector.text, got, vector.want)
			}
		})
	}

	rejection := selfAttributedDecisionMarker("The rejection was written by the model.", decisionKindRejection)
	if rejection == nil {
		t.Fatal("selfAttributedDecisionMarker(rejection) = nil, want marker")
	}
	if rejection.category != "model-authored-decision" {
		t.Fatalf("rejection marker category = %q, want model-authored-decision", rejection.category)
	}
}

func TestDecisionValidationUsesWholeCancellationVocabulary(t *testing.T) {
	t.Parallel()

	tests := []struct {
		text string
		want bool
	}{
		{text: "", want: true},
		{text: "Cancelled.", want: true},
		{text: "timed-out", want: true},
		{text: "user dismissed", want: true},
		{text: "cancel the standing order", want: false},
		{text: "The timeout was unexpected.", want: false},
		{text: "no response from the service", want: false},
	}
	for _, tt := range tests {
		if got := isNonAnswer(tt.text); got != tt.want {
			t.Errorf("isNonAnswer(%q) = %v, want %v", tt.text, got, tt.want)
		}
	}
}

func TestDecisionValidationUsesECMAScriptTrimBoundaries(t *testing.T) {
	t.Parallel()

	if err := validateApprovalChoice("\ufeffApprove\ufeff", 0); err != nil {
		t.Fatalf("Approve with BOM trim error = %v, want nil", err)
	}
	if err := validateApprovalChoice("\u0085Approve\u0085", 0); !errors.Is(err, ErrInvalidDecision) {
		t.Fatalf("Approve with U+0085 error = %v, want ErrInvalidDecision", err)
	}
	if err := validateApprovalChoice("\ufeffAccept as-is\ufeff", 3); err != nil {
		t.Fatalf("Accept as-is with BOM trim error = %v, want nil", err)
	}
	if err := validateApprovalChoice("\u0085Accept as-is\u0085", 3); !errors.Is(err, ErrInvalidDecision) {
		t.Fatalf("Accept as-is with U+0085 error = %v, want ErrInvalidDecision", err)
	}

	choice, feedback, err := validateRejectionDecision("\ufeffRequest Changes\ufeff", "\ufeffNeeds revision\ufeff")
	if err != nil {
		t.Fatalf("Request Changes with BOM trim error = %v, want nil", err)
	}
	if choice != "Request Changes" || feedback != "Needs revision" {
		t.Fatalf("BOM-trimmed rejection = (%q, %q), want (Request Changes, Needs revision)", choice, feedback)
	}
	if _, _, err := validateRejectionDecision("\u0085Request Changes\u0085", "Needs revision"); !errors.Is(err, ErrInvalidDecision) {
		t.Fatalf("Request Changes with U+0085 error = %v, want ErrInvalidDecision", err)
	}
	if isNonAnswer("\ufeffCancelled\ufeff") != true {
		t.Fatal("isNonAnswer(BOM-wrapped Cancelled) = false, want true")
	}
	if isNonAnswer("\u0085Cancelled\u0085") {
		t.Fatal("isNonAnswer(U+0085-wrapped Cancelled) = true, want false")
	}
}

func stringsForDecisionState(t *testing.T) []byte {
	t.Helper()
	return []byte(`# AI-DLC State Tracking

## Project Information
- **Project**: sample
- **Project Type**: Brownfield
- **Scope**: classic
- **State Version**: 8

## Execution Plan Summary
- **Total Stages**: 1
- **Completed**: 0
- **In Progress**: intent-capture

## Phase Progress
- **Initialization**: Verified
- **Ideation**: Active
- **Inception**: Pending
- **Construction**: Pending
- **Operation**: Pending

## Stage Progress
- [?] intent-capture — EXECUTE

## Current Status
- **Lifecycle Phase**: IDEATION
- **Current Stage**: intent-capture
- **Next Stage**: none
- **Status**: Running
- **Last Updated**: 2026-09-04T00:00:00Z

## Runtime State
- **Revision Count**: 0
`)
}
