package review

import (
	"bytes"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"path"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"
	"unicode/utf8"
)

var (
	ErrArtifactChanged   = errors.New("review: artifact changed")
	ErrMalformedAppendix = errors.New("review: malformed appendix")
	ErrExistingAppendix  = errors.New("review: artifact already has a review appendix")
	ErrInvalidRequest    = errors.New("review: invalid request")
)

type RequestInput struct {
	Stage            string
	Reviewer         string
	Iteration        int
	ArtifactPath     string
	ArtifactSnapshot []byte
	// ArtifactSnapshots contains the complete declared artifact set bound to
	// a review request. ArtifactSnapshot remains the review-artifact member for
	// appendix offset and prefix validation.
	ArtifactSnapshots map[string][]byte
	RequestSource     string
}

type Request struct {
	Stage               string
	Reviewer            string
	Iteration           int
	ArtifactPath        string
	ArtifactSnapshot    []byte
	ArtifactSnapshots   map[string][]byte
	ArtifactFingerprint string
	RequestFingerprint  string
	PriorDigest         string
	PriorLength         int64
	// ReviewChallenge is generated by the backend when a prior canonical
	// appendix must be replaced during a revision.
	ReviewChallenge string
	AppendixOffset  int64
	RequestSource   string
	// PriorAppendixRemoved is set only when the backend rehydrates a revision
	// request after the conductor has removed the old terminal appendix. The
	// request still binds its digest/length and challenge; the completion must
	// append a new canonical terminal at the same offset.
	PriorAppendixRemoved bool
}

type CompletionInput struct {
	Request       Request
	Verdict       string
	ArtifactAfter []byte
}

type Completion struct {
	Verdict         string
	ArtifactAfter   []byte
	AppendixOffset  int64
	PostFingerprint string
}

func NewRequest(input RequestInput) (Request, error) {
	if input.Stage == "" || input.Reviewer == "" || input.Iteration < 1 || input.ArtifactPath == "" {
		return Request{}, fmt.Errorf("review request fields are incomplete: %w", ErrInvalidRequest)
	}
	if !utf8.Valid(input.ArtifactSnapshot) {
		return Request{}, fmt.Errorf("review artifact snapshot is not UTF-8: %w", ErrInvalidRequest)
	}
	snapshot := append([]byte(nil), input.ArtifactSnapshot...)
	artifacts, err := normalizeArtifactSnapshots(input.Stage, input.ArtifactPath, snapshot, input.ArtifactSnapshots)
	if err != nil {
		return Request{}, err
	}
	appendixOffset := int64(len(snapshot))
	priorDigest := "none"
	priorLength := int64(0)
	reviewChallenge := ""
	if offset, appendix, found, err := existingReviewAppendix(snapshot, input.Stage, input.Reviewer, input.Iteration); err != nil {
		return Request{}, err
	} else if found {
		appendixOffset = int64(offset)
		evidence := reviewAppendixEvidenceBytes(appendix)
		if len(evidence) == 0 {
			return Request{}, fmt.Errorf("review request existing appendix is empty: %w", ErrMalformedAppendix)
		}
		priorDigest = "sha256:" + digestBytes(evidence)
		priorLength = int64(len(evidence))
		var challengeErr error
		reviewChallenge, challengeErr = newReviewChallenge()
		if challengeErr != nil {
			return Request{}, fmt.Errorf("review request challenge: %w", challengeErr)
		}
	}
	artifactFingerprint := digestArtifactSnapshotsAt(artifacts, input.ArtifactPath, appendixOffset)
	request := Request{
		Stage:               input.Stage,
		Reviewer:            input.Reviewer,
		Iteration:           input.Iteration,
		ArtifactPath:        input.ArtifactPath,
		ArtifactSnapshot:    snapshot,
		ArtifactSnapshots:   artifacts,
		ArtifactFingerprint: artifactFingerprint,
		PriorDigest:         priorDigest,
		PriorLength:         priorLength,
		ReviewChallenge:     reviewChallenge,
		AppendixOffset:      appendixOffset,
		RequestSource:       input.RequestSource,
	}
	// RequestFingerprint remains a source-compatible in-memory alias. It is
	// not emitted as a request-side audit field; ArtifactFingerprint is the
	// canonical request binding.
	request.RequestFingerprint = request.ArtifactFingerprint
	return request, nil
}

func NewCompletion(input CompletionInput) (Completion, error) {
	if err := ValidateRequest(input.Request); err != nil {
		return Completion{}, err
	}
	postSnapshots := cloneArtifactSnapshots(input.Request.ArtifactSnapshots)
	if len(postSnapshots) == 0 {
		postSnapshots = map[string][]byte{input.Request.ArtifactPath: append([]byte(nil), input.Request.ArtifactSnapshot...)}
	}
	postSnapshots[input.Request.ArtifactPath] = append([]byte(nil), input.ArtifactAfter...)
	completion := Completion{
		Verdict:         input.Verdict,
		ArtifactAfter:   append([]byte(nil), input.ArtifactAfter...),
		AppendixOffset:  input.Request.AppendixOffset,
		PostFingerprint: digestArtifactSnapshots(postSnapshots),
	}
	if err := ValidateCompletion(input.Request, completion); err != nil {
		return Completion{}, err
	}
	return completion, nil
}

func ValidateRequest(request Request) error {
	if request.Stage == "" || request.Reviewer == "" || request.Iteration < 1 || request.ArtifactPath == "" || request.PriorLength < 0 || request.AppendixOffset < 0 {
		return fmt.Errorf("review request fields are incomplete: %w", ErrInvalidRequest)
	}
	artifacts, err := normalizeArtifactSnapshots(request.Stage, request.ArtifactPath, request.ArtifactSnapshot, request.ArtifactSnapshots)
	if err != nil {
		return err
	}
	if request.AppendixOffset > int64(len(request.ArtifactSnapshot)) {
		return fmt.Errorf("review request appendix offset is outside the review artifact: %w", ErrArtifactChanged)
	}
	if request.PriorLength == 0 {
		if request.PriorDigest != "none" || request.ReviewChallenge != "" || request.AppendixOffset != int64(len(request.ArtifactSnapshot)) || hasReviewAppendix(request.ArtifactSnapshot) {
			return fmt.Errorf("review request prior appendix binding is invalid: %w", ErrArtifactChanged)
		}
	} else {
		if request.PriorDigest == "none" || !reviewAppendixDigestPattern.MatchString(request.PriorDigest) || request.ReviewChallenge == "" || !reviewChallengePattern.MatchString(request.ReviewChallenge) {
			return fmt.Errorf("review request revision binding is incomplete: %w", ErrArtifactChanged)
		}
		if request.AppendixOffset > int64(len(request.ArtifactSnapshot)) || request.AppendixOffset == int64(len(request.ArtifactSnapshot)) && !request.PriorAppendixRemoved {
			return fmt.Errorf("review request revision has no prior appendix: %w", ErrArtifactChanged)
		}
		if !request.PriorAppendixRemoved {
			prior := request.ArtifactSnapshot[request.AppendixOffset:]
			evidence := reviewAppendixEvidenceBytes(prior)
			if int64(len(evidence)) != request.PriorLength || "sha256:"+digestBytes(evidence) != request.PriorDigest {
				return fmt.Errorf("review request prior appendix binding is stale: %w", ErrArtifactChanged)
			}
			if _, _, found, err := existingReviewAppendix(request.ArtifactSnapshot, request.Stage, request.Reviewer, request.Iteration); err != nil || !found {
				if err != nil {
					return err
				}
				return fmt.Errorf("review request prior appendix is not canonical: %w", ErrMalformedAppendix)
			}
		}
	}
	if digestArtifactSnapshotsAt(artifacts, request.ArtifactPath, request.AppendixOffset) != request.ArtifactFingerprint || (request.RequestFingerprint != "" && request.RequestFingerprint != request.ArtifactFingerprint) {
		return fmt.Errorf("review request snapshot or fingerprint is stale: %w", ErrArtifactChanged)
	}
	return nil
}

func ValidateCompletion(request Request, completion Completion) error {
	if err := ValidateRequest(request); err != nil {
		return err
	}
	postSnapshots := cloneArtifactSnapshots(request.ArtifactSnapshots)
	if len(postSnapshots) == 0 {
		postSnapshots = map[string][]byte{request.ArtifactPath: append([]byte(nil), request.ArtifactSnapshot...)}
	}
	postSnapshots[request.ArtifactPath] = append([]byte(nil), completion.ArtifactAfter...)
	if completion.PostFingerprint == "" || completion.PostFingerprint != digestArtifactSnapshots(postSnapshots) {
		return fmt.Errorf("review completion fingerprint is stale or missing: %w", ErrArtifactChanged)
	}
	if completion.Verdict != "READY" && completion.Verdict != "NOT-READY" {
		return fmt.Errorf("review verdict %q is invalid: %w", completion.Verdict, ErrMalformedAppendix)
	}
	if completion.AppendixOffset != request.AppendixOffset || completion.AppendixOffset < 0 || completion.AppendixOffset > int64(len(completion.ArtifactAfter)) {
		return fmt.Errorf("review appendix offset is invalid: %w", ErrMalformedAppendix)
	}
	if completion.AppendixOffset > int64(len(request.ArtifactSnapshot)) || completion.AppendixOffset > int64(len(completion.ArtifactAfter)) || !bytes.Equal(completion.ArtifactAfter[:request.AppendixOffset], request.ArtifactSnapshot[:request.AppendixOffset]) {
		return fmt.Errorf("review artifact prefix changed: %w", ErrArtifactChanged)
	}
	if request.PriorLength > 0 && !request.PriorAppendixRemoved {
		oldEvidence := reviewAppendixEvidenceBytes(request.ArtifactSnapshot[request.AppendixOffset:])
		newEvidence := reviewAppendixEvidenceBytes(completion.ArtifactAfter[request.AppendixOffset:])
		if len(oldEvidence) != 0 && bytes.HasPrefix(newEvidence, oldEvidence) {
			return fmt.Errorf("review completion replays the prior appendix: %w", ErrArtifactChanged)
		}
	}
	suffix := string(completion.ArtifactAfter[completion.AppendixOffset:])
	if err := validateAppendix(suffix, request, completion.Verdict, request.ReviewChallenge, false); err != nil {
		return err
	}
	return nil
}

func validateAppendix(suffix string, request Request, verdict, expectedChallenge string, allowExistingChallenge bool) error {
	suffix = strings.ReplaceAll(strings.ReplaceAll(suffix, "\r\n", "\n"), "\r", "\n")
	for len(suffix) > 0 {
		lineEnd := strings.IndexByte(suffix, '\n')
		if lineEnd < 0 || strings.TrimSpace(suffix[:lineEnd]) != "" {
			break
		}
		suffix = suffix[lineEnd+1:]
	}
	if !strings.HasPrefix(suffix, "## Review\n") {
		return fmt.Errorf("review appendix has no terminal heading: %w", ErrMalformedAppendix)
	}
	lines := reviewVisibleMarkdownLines(strings.TrimSuffix(suffix, "\n"))
	if len(lines) == 0 || strings.TrimSpace(lines[0]) != "## Review" {
		return fmt.Errorf("review appendix has no canonical terminal heading: %w", ErrMalformedAppendix)
	}
	want := map[string]string{
		"Verdict":           "**Verdict:** " + verdict,
		"Reviewer":          "**Reviewer:** " + request.Reviewer,
		"Date":              "",
		"Iteration":         fmt.Sprintf("**Iteration:** %d", request.Iteration),
		"Request Challenge": "",
	}
	seen := make(map[string]bool, len(want))
	authorityOrder := map[string]int{"Verdict": 0, "Reviewer": 1, "Date": 2, "Iteration": 3, "Request Challenge": 4}
	lastAuthority := -1
	findingsIndex := -1
	summaryIndex := -1
	authorityBlock := true
	for index, raw := range lines {
		line := strings.TrimSpace(raw)
		if !reviewTopLevelLine(raw) {
			continue
		}
		if index > 0 && (strings.HasPrefix(line, "# ") || strings.HasPrefix(line, "## ") || reviewRawHTMLHeading(line)) {
			return fmt.Errorf("review appendix escapes its terminal section: %w", ErrMalformedAppendix)
		}
		if index > 0 && index+1 < len(lines) && reviewTopLevelLine(lines[index+1]) && reviewSetextHeading(line, strings.TrimSpace(lines[index+1])) {
			return fmt.Errorf("review appendix escapes its terminal section: %w", ErrMalformedAppendix)
		}
		if line == "" {
			continue
		}
		if strings.HasPrefix(line, "### ") && line != "### Findings" && line != "### Summary" {
			return fmt.Errorf("review appendix has an unexpected subsection: %w", ErrMalformedAppendix)
		}
		if line == "### Findings" {
			if findingsIndex >= 0 {
				return fmt.Errorf("review appendix repeats findings section: %w", ErrMalformedAppendix)
			}
			findingsIndex = index
			authorityBlock = false
		}
		if line == "### Summary" {
			if summaryIndex >= 0 {
				return fmt.Errorf("review appendix repeats summary section: %w", ErrMalformedAppendix)
			}
			summaryIndex = index
		}
		if !authorityBlock && strings.HasPrefix(line, "**") && (strings.HasPrefix(line, "**Verdict:**") || strings.HasPrefix(line, "**Reviewer:**") || strings.HasPrefix(line, "**Date:**") || strings.HasPrefix(line, "**Iteration:**") || strings.HasPrefix(line, "**Request Challenge:**")) {
			return fmt.Errorf("review appendix authority field is outside its direct block: %w", ErrMalformedAppendix)
		}
		for key, prefix := range map[string]string{
			"Verdict":           "**Verdict:**",
			"Reviewer":          "**Reviewer:**",
			"Date":              "**Date:**",
			"Iteration":         "**Iteration:**",
			"Request Challenge": "**Request Challenge:**",
		} {
			if !strings.HasPrefix(line, prefix) {
				continue
			}
			if !authorityBlock {
				return fmt.Errorf("review appendix authority field is outside its direct block: %w", ErrMalformedAppendix)
			}
			if seen[key] {
				return fmt.Errorf("review appendix duplicates %s: %w", key, ErrMalformedAppendix)
			}
			if authorityOrder[key] <= lastAuthority {
				return fmt.Errorf("review appendix authority fields are out of order: %w", ErrMalformedAppendix)
			}
			lastAuthority = authorityOrder[key]
			seen[key] = true
			if key == "Date" {
				dateValue := strings.TrimSpace(strings.TrimPrefix(line, prefix))
				parsed, err := time.Parse(time.RFC3339, dateValue)
				if err != nil || parsed.IsZero() {
					return fmt.Errorf("review appendix date is not RFC3339: %w", ErrMalformedAppendix)
				}
				want[key] = line
				continue
			}
			if key == "Request Challenge" {
				challenge := strings.TrimSpace(strings.TrimPrefix(line, prefix))
				if !reviewChallengePattern.MatchString(challenge) {
					return fmt.Errorf("review appendix request challenge is invalid: %w", ErrMalformedAppendix)
				}
				if expectedChallenge != "" && challenge != expectedChallenge {
					return fmt.Errorf("review appendix request challenge does not match request: %w", ErrMalformedAppendix)
				}
				want[key] = line
				continue
			}
			if line != want[key] {
				return fmt.Errorf("review appendix %s does not exactly match request: %w", key, ErrMalformedAppendix)
			}
		}
	}
	for _, key := range []string{"Verdict", "Reviewer", "Date", "Iteration"} {
		if !seen[key] {
			return fmt.Errorf("review appendix is missing %s: %w", key, ErrMalformedAppendix)
		}
	}
	if expectedChallenge != "" && !seen["Request Challenge"] {
		return fmt.Errorf("review appendix is missing Request Challenge: %w", ErrMalformedAppendix)
	}
	if expectedChallenge == "" && !allowExistingChallenge && seen["Request Challenge"] {
		return fmt.Errorf("review appendix must omit Request Challenge for an initial request: %w", ErrMalformedAppendix)
	}
	if findingsIndex < 0 || summaryIndex < 0 || findingsIndex >= summaryIndex {
		return fmt.Errorf("review appendix findings and summary sections are incomplete: %w", ErrMalformedAppendix)
	}
	header := "| ID | Severity | Location | Finding | Required action | Status |"
	separator := "|---|---|---|---|---|---|"
	foundHeader := false
	foundSeparator := false
	headerCount := 0
	separatorCount := 0
	for _, raw := range lines[findingsIndex+1 : summaryIndex] {
		line := strings.TrimSpace(raw)
		if line == header {
			foundHeader = true
			headerCount++
		}
		if line == separator {
			foundSeparator = true
			separatorCount++
		}
	}
	if !foundHeader || !foundSeparator || headerCount != 1 || separatorCount != 1 {
		return fmt.Errorf("review appendix findings table is incomplete: %w", ErrMalformedAppendix)
	}
	for _, raw := range lines[summaryIndex+1:] {
		if strings.TrimSpace(raw) != "" {
			return nil
		}
	}
	return fmt.Errorf("review appendix summary is empty: %w", ErrMalformedAppendix)
}

func hasReviewAppendix(content []byte) bool {
	if !utf8.Valid(content) {
		return false
	}
	for _, raw := range reviewVisibleMarkdownLines(string(content)) {
		line := strings.TrimSpace(raw)
		if line == "## Review" && reviewTopLevelLine(raw) {
			return true
		}
	}
	return false
}

// existingReviewAppendix locates and validates the current canonical terminal
// appendix. A revision request snapshots the bytes before this heading while
// retaining the complete observed artifact so the record writer can verify
// that the user has not changed it between request construction and append.
func existingReviewAppendix(content []byte, stage, reviewer string, _ int) (int, []byte, bool, error) {
	lines, offsets := reviewRawLines(content)
	visible := reviewVisibleMarkdownLines(string(content))
	terminalIndexes := make([]int, 0, 1)
	for index := range lines {
		if index < len(visible) && strings.TrimSpace(visible[index]) == "## Review" && reviewTopLevelLine(lines[index]) {
			terminalIndexes = append(terminalIndexes, index)
		}
	}
	if len(terminalIndexes) == 0 {
		return 0, nil, false, nil
	}
	if len(terminalIndexes) != 1 {
		return 0, nil, false, fmt.Errorf("review artifact has multiple terminal appendices: %w", ErrMalformedAppendix)
	}
	index := terminalIndexes[0]
	offset := offsets[index]
	iteration, err := appendixIteration(string(content[offset:]))
	if err != nil {
		return 0, nil, false, err
	}
	request := Request{Stage: stage, Reviewer: reviewer, Iteration: iteration}
	verdict, err := appendixVerdict(string(content[offset:]))
	if err != nil {
		return 0, nil, false, err
	}
	if err := validateAppendix(string(content[offset:]), request, verdict, "", true); err != nil {
		return 0, nil, false, fmt.Errorf("review request existing appendix is not canonical: %w", err)
	}
	return offset, append([]byte(nil), content[offset:]...), true, nil
}

// reviewAppendixEvidenceBytes removes only the permitted blank separator
// bytes before a terminal heading. The pinned length/digest therefore covers
// the canonical appendix itself, not incidental spacing used to append it.
func reviewAppendixEvidenceBytes(appendix []byte) []byte {
	start := 0
	for start < len(appendix) {
		lineEnd := start
		for lineEnd < len(appendix) && appendix[lineEnd] != '\n' && appendix[lineEnd] != '\r' {
			lineEnd++
		}
		if strings.TrimSpace(string(appendix[start:lineEnd])) != "" {
			break
		}
		if lineEnd == len(appendix) {
			return appendix[len(appendix):]
		}
		if appendix[lineEnd] == '\r' && lineEnd+1 < len(appendix) && appendix[lineEnd+1] == '\n' {
			lineEnd++
		}
		start = lineEnd + 1
	}
	return appendix[start:]
}

func reviewRawLines(content []byte) ([]string, []int) {
	lines := make([]string, 0, 8)
	offsets := make([]int, 0, 8)
	start := 0
	for start <= len(content) {
		end := start
		for end < len(content) && content[end] != '\n' && content[end] != '\r' {
			end++
		}
		lines = append(lines, string(content[start:end]))
		offsets = append(offsets, start)
		if end == len(content) {
			break
		}
		if content[end] == '\r' && end+1 < len(content) && content[end+1] == '\n' {
			end++
		}
		start = end + 1
	}
	return lines, offsets
}

func appendixVerdict(suffix string) (string, error) {
	lines := reviewVisibleMarkdownLines(suffix)
	verdict := ""
	for _, raw := range lines {
		line := strings.TrimSpace(raw)
		const prefix = "**Verdict:**"
		if !strings.HasPrefix(line, prefix) {
			continue
		}
		if verdict != "" {
			return "", fmt.Errorf("review appendix repeats Verdict: %w", ErrMalformedAppendix)
		}
		value := strings.TrimSpace(strings.TrimPrefix(line, prefix))
		if value != "READY" && value != "NOT-READY" {
			return "", fmt.Errorf("review appendix verdict is invalid: %w", ErrMalformedAppendix)
		}
		verdict = value
	}
	if verdict == "" {
		return "", fmt.Errorf("review appendix is missing Verdict: %w", ErrMalformedAppendix)
	}
	return verdict, nil
}

func appendixIteration(suffix string) (int, error) {
	const prefix = "**Iteration:**"
	iteration := 0
	for _, raw := range reviewVisibleMarkdownLines(suffix) {
		line := strings.TrimSpace(raw)
		if !strings.HasPrefix(line, prefix) {
			continue
		}
		if iteration != 0 {
			return 0, fmt.Errorf("review appendix repeats Iteration: %w", ErrMalformedAppendix)
		}
		value, err := strconv.Atoi(strings.TrimSpace(strings.TrimPrefix(line, prefix)))
		if err != nil || value < 1 {
			return 0, fmt.Errorf("review appendix iteration is invalid: %w", ErrMalformedAppendix)
		}
		iteration = value
	}
	if iteration == 0 {
		return 0, fmt.Errorf("review appendix is missing Iteration: %w", ErrMalformedAppendix)
	}
	return iteration, nil
}

type reviewFence struct {
	marker byte
	length int
}

func reviewVisibleMarkdownLines(body string) []string {
	lines := strings.Split(strings.TrimPrefix(strings.ReplaceAll(body, "\r\n", "\n"), "\ufeff"), "\n")
	visible := make([]string, len(lines))
	var fence reviewFence
	comment := false
	for index, raw := range lines {
		line := stripReviewHTMLComments(raw, &comment)
		if fence.length != 0 {
			if reviewFenceClosed(line, fence) {
				fence = reviewFence{}
			}
			continue
		}
		if marker, ok := reviewFenceOpening(line); ok {
			fence = marker
			continue
		}
		visible[index] = stripReviewInlineCode(line)
	}
	return visible
}

func reviewFenceOpening(line string) (reviewFence, bool) {
	indent := len(line) - len(strings.TrimLeft(line, " "))
	if indent > 3 {
		return reviewFence{}, false
	}
	line = line[indent:]
	if len(line) < 3 || (line[0] != '`' && line[0] != '~') {
		return reviewFence{}, false
	}
	length := 0
	for length < len(line) && line[length] == line[0] {
		length++
	}
	if length < 3 {
		return reviewFence{}, false
	}
	return reviewFence{marker: line[0], length: length}, true
}

func reviewFenceClosed(line string, fence reviewFence) bool {
	indent := len(line) - len(strings.TrimLeft(line, " "))
	if indent > 3 {
		return false
	}
	line = line[indent:]
	if len(line) < fence.length || line[0] != fence.marker {
		return false
	}
	length := 0
	for length < len(line) && line[length] == fence.marker {
		length++
	}
	return length >= fence.length && strings.TrimSpace(line[length:]) == ""
}

func stripReviewHTMLComments(line string, inComment *bool) string {
	if inComment == nil {
		return line
	}
	var visible strings.Builder
	for offset := 0; offset < len(line); {
		if *inComment {
			end := strings.Index(line[offset:], "-->")
			if end < 0 {
				return visible.String()
			}
			offset += end + len("-->")
			*inComment = false
			continue
		}
		start := strings.Index(line[offset:], "<!--")
		if start < 0 {
			visible.WriteString(line[offset:])
			break
		}
		visible.WriteString(line[offset : offset+start])
		offset += start + len("<!--")
		*inComment = true
	}
	return visible.String()
}

func stripReviewInlineCode(line string) string {
	for start := 0; start < len(line); {
		relative := strings.IndexByte(line[start:], '`')
		if relative < 0 {
			return line
		}
		start += relative
		run := 1
		for start+run < len(line) && line[start+run] == '`' {
			run++
		}
		end := -1
		for search := start + run; search < len(line); {
			relative = strings.IndexByte(line[search:], '`')
			if relative < 0 {
				break
			}
			search += relative
			closeRun := 1
			for search+closeRun < len(line) && line[search+closeRun] == '`' {
				closeRun++
			}
			if closeRun == run {
				end = search + closeRun
				break
			}
			search += closeRun
		}
		if end < 0 {
			return line[:start]
		}
		line = line[:start] + strings.Repeat(" ", end-start) + line[end:]
		start = end
	}
	return line
}

func reviewTopLevelLine(raw string) bool {
	indent := len(raw) - len(strings.TrimLeft(raw, " "))
	if indent > 3 {
		return false
	}
	line := strings.TrimSpace(raw)
	if line == "" || strings.HasPrefix(line, ">") || strings.HasPrefix(line, "|") {
		return false
	}
	if reviewListMarker(line) {
		return false
	}
	return true
}

func reviewListMarker(line string) bool {
	if len(line) >= 2 && (line[0] == '-' || line[0] == '+' || line[0] == '*') && (line[1] == ' ' || line[1] == '\t') {
		return true
	}
	for index := 0; index < len(line) && index < 9; index++ {
		if line[index] < '0' || line[index] > '9' {
			break
		}
		if index+1 < len(line) && (line[index+1] == '.' || line[index+1] == ')') && index+2 < len(line) && (line[index+2] == ' ' || line[index+2] == '\t') {
			return true
		}
	}
	return false
}

func reviewRawHTMLHeading(line string) bool {
	line = strings.ToLower(strings.TrimSpace(line))
	if len(line) < 3 || line[0] != '<' || line[1] != 'h' || (line[2] != '1' && line[2] != '2') {
		return false
	}
	return len(line) == 3 || line[3] == '>' || line[3] == ' ' || line[3] == '\t' || line[3] == '/'
}

func reviewSetextHeading(line, next string) bool {
	if line == "" || len(next) < 3 {
		return false
	}
	marker := next[0]
	if marker != '=' && marker != '-' {
		return false
	}
	for _, value := range next {
		if byte(value) != marker {
			return false
		}
	}
	return true
}

func digest(value []byte) string {
	hash := sha256.Sum256(value)
	return hex.EncodeToString(hash[:])
}

func digestBytes(value []byte) string {
	return digest(value)
}

func requestDigest(request Request) string {
	var builder strings.Builder
	for _, value := range []string{request.Stage, request.Reviewer, fmt.Sprint(request.Iteration), request.ArtifactPath, request.PriorDigest, request.ArtifactFingerprint, fmt.Sprint(request.PriorLength), fmt.Sprint(request.AppendixOffset), request.RequestSource} {
		fmt.Fprintf(&builder, "%d:", len(value))
		builder.WriteString(value)
		builder.WriteByte(0)
	}
	return digest([]byte(builder.String()))
}

func normalizeArtifactSnapshots(stage, artifactPath string, artifactSnapshot []byte, supplied map[string][]byte) (map[string][]byte, error) {
	if artifactPath == "" {
		return nil, fmt.Errorf("review artifact path is empty: %w", ErrInvalidRequest)
	}
	if len(supplied) == 0 {
		return map[string][]byte{artifactPath: append([]byte(nil), artifactSnapshot...)}, nil
	}
	result := make(map[string][]byte, len(supplied))
	for name, snapshot := range supplied {
		if name == "" || !fs.ValidPath(name) || path.IsAbs(name) || strings.Contains(name, "\\") {
			return nil, fmt.Errorf("review artifact path %q is unsafe: %w", name, ErrInvalidRequest)
		}
		if !utf8.Valid(snapshot) {
			return nil, fmt.Errorf("review artifact snapshot %q is not UTF-8: %w", name, ErrInvalidRequest)
		}
		result[name] = append([]byte(nil), snapshot...)
	}
	main, ok := result[artifactPath]
	if !ok || !bytes.Equal(main, artifactSnapshot) {
		return nil, fmt.Errorf("review artifact set does not bind the review artifact: %w", ErrInvalidRequest)
	}
	if stage == "intent-capture" && len(result) > 1 {
		if err := validateIntentCaptureArtifactSet(artifactPath, result); err != nil {
			return nil, err
		}
	}
	return result, nil
}

func validateIntentCaptureArtifactSet(artifactPath string, snapshots map[string][]byte) error {
	if len(snapshots) != 3 {
		return fmt.Errorf("intent-capture review must bind three declared artifacts: %w", ErrInvalidRequest)
	}
	dir := path.Dir(artifactPath)
	want := map[string]struct{}{
		path.Join(dir, "intent-capture-questions.md"): {},
		path.Join(dir, "intent-statement.md"):         {},
		path.Join(dir, "stakeholder-map.md"):          {},
	}
	for name := range snapshots {
		if _, ok := want[name]; !ok {
			return fmt.Errorf("intent-capture review artifact %q is outside the declared set: %w", name, ErrInvalidRequest)
		}
	}
	return nil
}

func cloneArtifactSnapshots(snapshots map[string][]byte) map[string][]byte {
	if len(snapshots) == 0 {
		return nil
	}
	clone := make(map[string][]byte, len(snapshots))
	for name, snapshot := range snapshots {
		clone[name] = append([]byte(nil), snapshot...)
	}
	return clone
}

func digestArtifactSnapshots(snapshots map[string][]byte) string {
	return digestArtifactSnapshotsAt(snapshots, "", -1)
}

// digestArtifactSnapshotsAt mirrors the fixed review manifest: logical paths
// are deterministic, each entry carries a sha256 digest, and only the
// review-artifact target may be truncated at the request appendix boundary.
// The returned value is always a namespaced sha256 manifest fingerprint.
func digestArtifactSnapshotsAt(snapshots map[string][]byte, appendixArtifact string, appendixOffset int64) string {
	if len(snapshots) == 0 {
		return "sha256:" + digest(nil)
	}
	names := artifactSnapshotNames(snapshots, appendixArtifact)
	manifest := make([][2]string, 0, len(names))
	for _, name := range names {
		body := snapshots[name]
		if name == appendixArtifact && appendixOffset >= 0 {
			if appendixOffset > int64(len(body)) {
				return ""
			}
			body = body[:appendixOffset]
		}
		manifest = append(manifest, [2]string{name, "sha256:" + digest(body)})
	}
	encoded, err := json.Marshal(manifest)
	if err != nil {
		return ""
	}
	return "sha256:" + digest(encoded)
}

func artifactSnapshotNames(snapshots map[string][]byte, appendixArtifact string) []string {
	names := make([]string, 0, len(snapshots))
	if appendixArtifact != "" {
		dir := path.Dir(appendixArtifact)
		for _, base := range []string{"intent-capture-questions.md", "intent-statement.md", "stakeholder-map.md"} {
			name := path.Join(dir, base)
			if _, ok := snapshots[name]; ok {
				names = append(names, name)
			}
		}
	}
	seen := make(map[string]struct{}, len(names))
	for _, name := range names {
		seen[name] = struct{}{}
	}
	remaining := make([]string, 0, len(snapshots)-len(names))
	for name := range snapshots {
		if _, ok := seen[name]; !ok {
			remaining = append(remaining, name)
		}
	}
	sort.Strings(remaining)
	return append(names, remaining...)
}

// ArtifactSnapshotsFingerprint returns the deterministic fingerprint for a
// declared artifact set. It is used by the audit read model when it validates
// the current bytes after a reviewer completion.
func ArtifactSnapshotsFingerprint(snapshots map[string][]byte) string {
	return digestArtifactSnapshots(snapshots)
}

// ArtifactSnapshotsRequestFingerprint returns the deterministic manifest
// fingerprint used by a review request. The named appendix artifact is
// represented by its request-time prefix; every other declared artifact is
// represented in full.
func ArtifactSnapshotsRequestFingerprint(snapshots map[string][]byte, appendixArtifact string, appendixOffset int64) string {
	return digestArtifactSnapshotsAt(snapshots, appendixArtifact, appendixOffset)
}

var reviewAppendixDigestPattern = regexp.MustCompile(`^sha256:[0-9a-f]{64}$`)
var reviewChallengePattern = regexp.MustCompile(`^review:[0-9a-f]{32}$`)

var reviewChallengeRandom io.Reader = rand.Reader

func newReviewChallenge() (string, error) {
	var bytes [16]byte
	if _, err := io.ReadFull(reviewChallengeRandom, bytes[:]); err != nil {
		return "", err
	}
	return "review:" + hex.EncodeToString(bytes[:]), nil
}
